### ISSUE TITLE
fixes for new recipes version

### ISSUE THREAD

**Issue by topepo** [tidymodels/hardhat#117]
With `recipes` 0.1.8`, there is a revdep failure with 

     ERROR
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
      ── 1. Failure: Missing y value returns a 0 column tibble for `outcomes` (@test-m
      Expectation did not fail
      
      ℹ Writing skeleton files
      ✔ Setting active project to '/private/var/folders/lb/xhxqmcrd7gv302_b1pdfykh80000gn/T/RtmphsiPwv/model'
      ✔ Writing 'R/random_forest-constructor.R'
      ✔ Writing 'R/random_forest-fit.R'
      ✔ Writing 'R/random_forest-predict.R'
      ● Run `devtools::document()`
      ══ testthat results  ═══════════════════════════════════════════════════════════
      [ OK: 400 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 1 ]
      1. Failure: Missing y value returns a 0 column tibble for `outcomes` (@test-mold-recipe.R#185) 
      
      Error: testthat unit tests failed
      Execution halted

**Comment by DavisVaughan** [comment]
Closed by 9cb2abc30685940f4fa91d1b6f3488bf3780e451
