### ISSUE TITLE
Warning Message: The `x` argument of `as_tibble.matrix()` must have column names if `.name_repair` is omitted as of tibble 2.0.0.

### ISSUE THREAD

**Issue by mdancho84** [tidymodels/hardhat#136]
Getting an odd warning message related to `as_tibble.matrix()`. This also affects `workflows`.

```
The `x` argument of `as_tibble.matrix()` must have column names if `.name_repair` is omitted as of tibble 2.0.0.
Using compatibility `.name_repair`.
```

I believe it's during the `mold()` and `forge()` steps that convert the model matrix to tibble. 

## Reproducible Example

``` r
library(recipes)
library(hardhat)
library(dplyr)
library(lifecycle)

set.seed(123)
data <- tibble(
    date = seq.Date(as.Date("2011-01-01"), by = "month", length.out = 12),
    y    = rnorm(12) + 1:12 
)

recipe_spec <- recipe(y ~ date, data) %>%
    step_date(date, features = "month") %>%
    step_mutate(date_num = as.numeric(date)) %>%
    step_rm(date)

mld <- mold(recipe_spec, data)
#> Warning: The `x` argument of `as_tibble.matrix()` must have column names if `.name_repair` is omitted as of tibble 2.0.0.
#> Using compatibility `.name_repair`.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_warnings()` to see where this warning was generated.
```

<sup>Created on 2020-05-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

## Lifecycle Last Warning
I see that the issue is `tibble:::as_tibble.matrix(date_values)`. Likely occurs in the `model_frame()` function where `tibble::as_tibble()` is called on a matrix (model.frame). 

```
> lifecycle::last_warnings()
[[1]]
<deprecated>
message: The `x` argument of `as_tibble.matrix()` must have column names if `.name_repair` is omitted as of tibble 2.0.0.
Using compatibility `.name_repair`.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.
backtrace:
  1. hardhat::mold(recipe_spec, data)
  2. hardhat:::mold.recipe(recipe_spec, data)
  4. hardhat:::run_mold.recipe_blueprint(blueprint, data)
  5. blueprint$mold$process(blueprint = blueprint, data = data)
  7. recipes:::prep.recipe(blueprint$recipe, training = data, fresh = blueprint$fresh)
  9. recipes:::bake.step_date(x$steps[[i]], new_data = training)
 11. tibble:::as_tibble.matrix(date_values)
```

**Comment by DavisVaughan** [comment]
Can you try with dev recipes?

**Comment by mdancho84** [comment]
Yes! It's fixed in the dev version. Thanks so much Davis.

**Comment by mdancho84** [comment]
Hey, I'm actually getting it. I think that the reason it went away was because of the lifecycle package only displaying every 8 hours.

**Comment by DavisVaughan** [comment]
I can't seem to reproduce this

The backtrace seems to imply that it was coming from here:

>   9. recipes:::bake.step_date(x$steps[[i]], new_data = training)

But we fixed this in recipe 0.1.10 which has been on cran for awhile
https://github.com/tidymodels/recipes/commit/73f14814b763a2df07ccf59c9b96f7bacfcf0151

Could you please check one more time that this is still an issue? Like, install the cran version of recipes, restart R, then run that code in a reprex. Does it still throw the warning?

**Comment by mdancho84** [comment]
Hey Davis, 
I really apologize for wasting your time on this. I upgraded all of my packages, and the warning is no longer present. I believe this was due to a downgraded package. 

-Matt

**Comment by DavisVaughan** [comment]
Not a problem - glad it is fixed!
