### ISSUE TITLE
more specific name for get_predict_function

### ISSUE THREAD

**Issue by topepo** [tidymodels/hardhat#152]
If there are multiple modeling functions in a package created by `hardhat`, the user has to remember to rename `get_predict_function()` so that there are not conflicts. Most of the other functions have the model name in them.

**Comment by topepo** [comment]
Maybe the same for others too, such as `valid_predict_types()`

**Comment by DavisVaughan** [comment]
Those look to be the only two that dont have the model name in them. I think that change makes sense 👍 

`get_{{model}}_predict_function()`

`valid_{{model}}_predict_types()`
