### ISSUE TITLE
Error: Internal error: Unknown `composition` type.

### ISSUE THREAD

**Issue by DiabbZegpi** [tidymodels/hardhat#157]
## I have trouble with predict() function

I have a tidymodels workflow, built in december 2020 with a random forests model inside plus recipes. The model was reproducing predictions just fine in the computer where it was developed, but in march 2021 I tried to make predictions on a new computer and failed. I have read that there is a incompability between hardhat 0.1.5 and models fitted previous that release.

How can I fix this?

## Reproducible example
I'm just using predict() with new_data argument. I can't share models nor data.

**Comment by DavisVaughan** [comment]
I'm sorry you're having trouble! It is very difficult to help you without a reprex.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

I understand that you can't share your models, but if you could show an example where a model built with an old version of hardhat is now failing with the new version, then that would be helpful.


It would also help if we could see the output of `traceback()` or `rlang::last_trace()` after you get the error

**Comment by DiabbZegpi** [comment]
I'm sorry I didn't respond earlier. I've fixed the bug re-training my model with the updated version of tidymodels.
Thank you very much.
