### ISSUE TITLE
Consider allowing `vec_cast(<frequency_weights>, to = double())`

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/hardhat#193]
That won't ever be lossy, and would be helpful to be able to use these weights in `weighted_table()`, which is used by yardstick.

It might also make sense to have a general rule that all weights can be converted to double with `as.double()`.

Only integer-ish weights would be convertible to integer with `as.integer()`.

**Comment by EmilHvitfeldt** [comment]
This would also be helpful in {recipes} as there are steps that handles both types.
