### ISSUE TITLE
Less restrictive snapshot test for recipes

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/hardhat#243]
When I prepped the {recipes} release, I ended up temporarily undoing a change in an warning, because it would have otherwise stopped the release. If would be nice if we could make the hardhat test a little less fragile 

https://github.com/tidymodels/recipes/pull/1275/commits/55da6dc3433c6c59cba965c5deb725338733806e

corresponding {hardhat} test 

https://github.com/tidymodels/hardhat/blob/ac2dfd06e52bed75e4bca35fa1df0d93f3575a85/tests/testthat/test-forge-recipe.R#L163-L169

**Comment by DavisVaughan** [comment]
i think we should make them _actual_ snapshot tests, rather than `expect_warning()` calls
