### ISSUE TITLE
some additional validators/checks

### ISSUE THREAD

**Issue by topepo** [tidymodels/hardhat#98]
Some suggestions for things that will be commonly used, especially for checking arguments. 

- [ ] `validate_outcomes_are_numeric(x)`
- [ ] `validate_single_character(x)`
- [ ] `validate_single_logical(x)`
- [ ] `validate_single_integer(x)`
- [ ] `validate_single_numeric(x)`
- [ ] `validate_from_key(x, key)` (e.g. type is in `c("numeric", "class", ...)` and check type versus key type)

**Comment by DavisVaughan** [comment]
I'm torn between encouraging these simple ones `validate_single_character(x)` vs `vec_assert(x, character(), 1)` which I think is what would be encouraged (and is what that helper would use)

`validate_outcomes_are_numeric(x)` - I do think this one would be helpful
