### ISSUE TITLE
exclude code for test coverage

### ISSUE THREAD

**Issue by topepo** [tidymodels/hardhat#99]
When someone uses `hardhat` to make their own modeling package, it should exclude the `hardhat` code in the user's package from being used in calculating test coverage (e.g. the validation and check functions).

**Comment by DavisVaughan** [comment]
what section in particular? im not sure im following

**Comment by DavisVaughan** [comment]
the only validation function that the template inserts automatically for you is this one:
https://github.com/tidymodels/hardhat/blob/b5df2d60c65493b171a1d2d74be98a2ec73b6789/inst/templates/R/predict-bridge.R#L7

Are you saying that you'd wrap that in `# nocov` or whatever the comment is to turn off coverage? I don't think that would really do anything. As long as the function that the validation check is in gets tested (which it should be), then that line will be run no matter what so it would never count against you

**Comment by topepo** [comment]
Ok. That makes sense. For some reason, I thought that `hardhat` copied these functions over to the new package R directory.
